// <auto-generated />
using System;
using ApiThaoCamVien.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiThaoCamVien.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260417011427_AddAppClientPresence")]
    partial class AddAppClientPresence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedThaoCamVien.Models.AppClientPresence", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int?>("CurrentPoiId")
                        .HasColumnType("int")
                        .HasColumnName("current_poi_id");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("last_seen_utc");

                    b.HasKey("SessionId")
                        .HasName("PK_app_client_presence");

                    b.ToTable("app_client_presence", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.Poi", b =>
                {
                    b.Property<int>("PoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("poi_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoiId"));

                    b.Property<string>("AudioCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageThumbnail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_thumbnail");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("priority");

                    b.Property<int?>("Radius")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15)
                        .HasColumnName("radius");

                    b.HasKey("PoiId")
                        .HasName("PK__pois__6176E7AC68F9D4D2");

                    b.HasIndex("CategoryId");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiAudio", b =>
                {
                    b.Property<int>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AudioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AudioId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<float?>("DurationSeconds")
                        .HasColumnType("real")
                        .HasColumnName("DurationSeconds");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FilePath");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSizeBytes");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<int>("PoiId")
                        .HasColumnType("int")
                        .HasColumnName("PoiId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("AudioId")
                        .HasName("PK_PoiAudios");

                    b.HasIndex("PoiId");

                    b.ToTable("PoiAudios", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.HasKey("CategoryId")
                        .HasName("PK__poi_cate__D54EE9B48CAB2166");

                    b.ToTable("poi_category", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiMedium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("language");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("media_url");

                    b.Property<int>("PoiId")
                        .HasColumnType("int")
                        .HasColumnName("poi_id");

                    b.HasKey("MediaId")
                        .HasName("PK__poi_medi__D0A840F456B70667");

                    b.HasIndex("PoiId");

                    b.ToTable("poi_media", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiTranslation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("translation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PoiId")
                        .HasColumnType("int")
                        .HasColumnName("poi_id");

                    b.HasKey("TranslationId")
                        .HasName("PK_poi_translations");

                    b.HasIndex("PoiId");

                    b.ToTable("poi_translations", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiVisitHistory", b =>
                {
                    b.Property<long>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VisitId"));

                    b.Property<int?>("ListenDuration")
                        .HasColumnType("int");

                    b.Property<int?>("PoiId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitId")
                        .HasName("PK__poi_visi__375A75E1DEEE7CA0");

                    b.HasIndex("PoiId");

                    b.HasIndex("UserId");

                    b.ToTable("poi_visit_history", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.QrCode", b =>
                {
                    b.Property<int>("QrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QrId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PoiId")
                        .HasColumnType("int")
                        .HasColumnName("poi_id");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QrId")
                        .HasName("PK__qr_codes__6CD5101BE1633F49");

                    b.HasIndex("PoiId");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TourId")
                        .HasName("PK__tour__4B16B9E665B63F6D");

                    b.ToTable("tour", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.TourPoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PoiId")
                        .HasColumnType("int");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__tour_poi__3213E83FE13266EB");

                    b.HasIndex("PoiId");

                    b.HasIndex("TourId");

                    b.ToTable("tour_poi", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F89EDFDDA");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.UserLocationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_loc__3213E83F20760A9F");

                    b.HasIndex("UserId");

                    b.ToTable("user_location_log", (string)null);
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.Poi", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.PoiCategory", null)
                        .WithMany("Pois")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_pois_category");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiAudio", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany("PoiAudios")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PoiAudios_Pois");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiMedium", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .IsRequired()
                        .HasConstraintName("FK_media_poi");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiTranslation", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_translations_poi");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiVisitHistory", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .HasConstraintName("FK_visit_poi");

                    b.HasOne("SharedThaoCamVien.Models.User", "User")
                        .WithMany("PoiVisitHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_visit_user");

                    b.Navigation("Poi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.QrCode", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .IsRequired()
                        .HasConstraintName("FK_qr_poi");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.TourPoi", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.Poi", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .HasConstraintName("FK_tourpoi_poi");

                    b.HasOne("SharedThaoCamVien.Models.Tour", "Tour")
                        .WithMany("TourPois")
                        .HasForeignKey("TourId")
                        .HasConstraintName("FK_tourpoi_tour");

                    b.Navigation("Poi");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.UserLocationLog", b =>
                {
                    b.HasOne("SharedThaoCamVien.Models.User", "User")
                        .WithMany("UserLocationLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_location_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.Poi", b =>
                {
                    b.Navigation("PoiAudios");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.PoiCategory", b =>
                {
                    b.Navigation("Pois");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.Tour", b =>
                {
                    b.Navigation("TourPois");
                });

            modelBuilder.Entity("SharedThaoCamVien.Models.User", b =>
                {
                    b.Navigation("PoiVisitHistories");

                    b.Navigation("UserLocationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
