namespace AppThaoCamVien.Services
{
    public static class LanguageManager
    {
        public static readonly List<(string Code, string Flag, string Label)> Languages =
        [
            ("vi", "🇻🇳", "VI"), ("en", "🇬🇧", "EN"), 
            ("th", "🇹🇭", "TH"), ("id", "🇮🇩", "ID"), ("ms", "🇲🇾", "MS"), ("km", "🇰🇭", "KM"),
        ];

        public static void Load() => Apply(Preferences.Get("AppLang", "vi"));
        public static string Current => Preferences.Get("AppLang", "vi");

        public static void Apply(string lang)
        {
            Preferences.Set("AppLang", lang);
            var r = Application.Current?.Resources;
            if (r == null) return;
            // Giao diện chính: ja dùng bản en làm nền (có thể bổ sung bản dịch đầy đủ sau)
            var mainLang = lang == "ja" ? "en" : lang;
            foreach (var kv in Strings(mainLang)) r[kv.Key] = kv.Value;
            foreach (var kv in OnboardingStringCatalog.ForLang(lang)) r[kv.Key] = kv.Value;
        }

        private static Dictionary<string, string> Strings(string lang) => lang switch
        {
            "en" => new()
            {
                // Tabs
                ["TabHome"] = "Home",
                ["TabQR"] = "Scan QR",
                ["TabNumpad"] = "Code",
                ["TabStory"] = "Animals",
                ["TabMap"] = "Map",
                ["TabAbout"] = "About",
                // Home
                ["TxtZooName"] = "SAIGON ZOO & BOTANICAL GARDENS",
                ["TxtAudioGuide"] = "AUDIO GUIDE TOUR",
                ["TxtHeroTitle"] = "The Sound Journey",
                ["TxtHeroAddress"] = "2 Nguyen Binh Khiem, District 1",
                ["TxtStartTour"] = "START YOUR JOURNEY  ▶",
                ["TxtOpenHours"] = "🕐 Opening Hours",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "Open every day",
                ["TxtTicketTitle"] = "🎟️ Entrance Fee",
                ["TxtTicketFree"] = "Under 1m: Free",
                ["TxtTicketChild"] = "1m - 1.3m: 40,000₫",
                ["TxtTicketAdult"] = "Over 1.3m: 60,000₫",
                ["TxtChooseTour"] = "CHOOSE YOUR TOUR",
                ["TxtViewAll"] = "View all",
                ["TxtTour1Title"] = "Asian Elephant Kingdom",
                ["TxtTour2Title"] = "King of the Jungle",
                ["TxtTour3Title"] = "The African Giant",
                ["TxtListenNow"] = "🔊 LISTEN NOW",
                ["TxtVoice"] = "Voice",
                ["TxtLyrics"] = "Lyrics",
                ["TxtHappeningNow"] = "Happening now",
                ["TxtRecommendedForYou"] = "Recommended for you",
                ["TxtWeatherAtZoo"] = "Weather at the zoo",
                // Animals
                ["TxtAnimalKingdom"] = "🌿 Animal Kingdom",
                ["TxtAnimalDesc"] = "Discover the amazing world of wildlife at Saigon Zoo",
                ["TxtSearchPlaceholder"] = "Search animals...",
                // Story
                ["TxtInfo"] = "Info",
                ["TxtImages"] = "Gallery",
                ["TxtMap"] = "Map",
                ["TxtEnclosure"] = "Enclosure Location",
                // Numpad
                ["TxtNumpadTitle"] = "Enter Code",
                ["TxtNumpadInstruction"] = "Enter the code on the sign",
                // QR
                ["TxtQrTitle"] = "Scan at enclosure",
                ["TxtQrInstruction"] = "Point camera at QR code",
                ["TxtQrSearching"] = "Searching for QR code...",
                ["TxtFlash"] = "Flash",
                ["TxtManualCode"] = "Enter code",
                // Map
                ["TxtMapTitle"] = "🗺️ Zoo Map",
                ["TxtAttractions"] = "Attractions",
                ["TxtPoints"] = "points",
                ["TxtListenBtn"] = "🔊 Listen",
                ["TxtInZone"] = "● In zone",
                ["TxtApproaching"] = "○ Approaching",
                // About
                ["TxtAboutApp"] = "About",
                ["TxtAppVersion"] = "Version 1.0.0",
                ["TxtAboutTitle"] = "About the app",
                ["TxtAboutDesc"] = "Smart audio guide for Saigon Zoo. GPS-based auto narration, QR scan, multilingual support.",
                ["TxtDeveloper"] = "Developed by: Dũng Nguyễn",
                ["TxtAppInfo"] = "App Information",
            },
            "th" => new()
            {
                ["TabHome"] = "หน้าแรก",
                ["TabQR"] = "สแกน QR",
                ["TabNumpad"] = "รหัส",
                ["TabStory"] = "สัตว์",
                ["TabMap"] = "แผนที่",
                ["TabAbout"] = "เกี่ยวกับ",
                ["TxtZooName"] = "สวนสัตว์ไซง่อน",
                ["TxtAudioGuide"] = "นำเที่ยวด้วยเสียง",
                ["TxtHeroTitle"] = "การเดินทางแห่งเสียง",
                ["TxtHeroAddress"] = "2 Nguyen Binh Khiem เขต 1",
                ["TxtStartTour"] = "เริ่มการเดินทาง  ▶",
                ["TxtOpenHours"] = "🕐 เวลาเปิด",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "เปิดทุกวัน",
                ["TxtTicketTitle"] = "🎟️ ค่าเข้าชม",
                ["TxtTicketFree"] = "ต่ำกว่า 1ม: ฟรี",
                ["TxtTicketChild"] = "1ม-1.3ม: 40,000₫",
                ["TxtTicketAdult"] = "สูงกว่า 1.3ม: 60,000₫",
                ["TxtChooseTour"] = "เลือกทัวร์ของคุณ",
                ["TxtViewAll"] = "ดูทั้งหมด",
                ["TxtTour1Title"] = "อาณาจักรช้างเอเชีย",
                ["TxtTour2Title"] = "ราชาแห่งป่า",
                ["TxtTour3Title"] = "ยักษ์แอฟริกา",
                ["TxtListenNow"] = "🔊 ฟังเลย",
                ["TxtAnimalKingdom"] = "🌿 อาณาจักรสัตว์",
                ["TxtAnimalDesc"] = "ค้นพบโลกสัตว์ป่าที่น่าทึ่ง",
                ["TxtSearchPlaceholder"] = "ค้นหาสัตว์...",
                ["TxtInfo"] = "ข้อมูล",
                ["TxtImages"] = "รูปภาพ",
                ["TxtMap"] = "แผนที่",
                ["TxtEnclosure"] = "ที่ตั้งกรง",
                ["TxtNumpadTitle"] = "ใส่รหัส",
                ["TxtNumpadInstruction"] = "ใส่รหัสบนป้าย",
                ["TxtQrTitle"] = "สแกนที่กรงสัตว์",
                ["TxtQrInstruction"] = "ชี้กล้องที่ QR",
                ["TxtQrSearching"] = "กำลังค้นหา QR...",
                ["TxtFlash"] = "แฟลช",
                ["TxtManualCode"] = "ใส่รหัส",
                ["TxtMapTitle"] = "🗺️ แผนที่สวนสัตว์",
                ["TxtAttractions"] = "สถานที่",
                ["TxtPoints"] = "จุด",
                ["TxtListenBtn"] = "🔊 ฟัง",
                ["TxtInZone"] = "● ในพื้นที่",
                ["TxtApproaching"] = "○ กำลังเข้าใกล้",
                ["TxtAboutApp"] = "เกี่ยวกับ",
                ["TxtAppVersion"] = "เวอร์ชัน 1.0.0",
                ["TxtAboutTitle"] = "เกี่ยวกับแอป",
                ["TxtAboutDesc"] = "แอปนำเที่ยวสวนสัตว์ไซง่อนด้วยเสียงอัจฉริยะ",
                ["TxtDeveloper"] = "พัฒนาโดย: Dũng Nguyễn",
                ["TxtAppInfo"] = "ข้อมูลแอป",
            },
            "id" => new()
            {
                ["TabHome"] = "Beranda",
                ["TabQR"] = "Pindai QR",
                ["TabNumpad"] = "Kode",
                ["TabStory"] = "Hewan",
                ["TabMap"] = "Peta",
                ["TabAbout"] = "Tentang",
                ["TxtZooName"] = "KEBUN BINATANG SAIGON",
                ["TxtAudioGuide"] = "PANDUAN AUDIO",
                ["TxtHeroTitle"] = "Perjalanan Suara",
                ["TxtHeroAddress"] = "2 Nguyen Binh Khiem",
                ["TxtStartTour"] = "MULAI PERJALANAN  ▶",
                ["TxtOpenHours"] = "🕐 Jam Buka",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "Buka setiap hari",
                ["TxtTicketTitle"] = "🎟️ Harga Tiket",
                ["TxtTicketFree"] = "Di bawah 1m: Gratis",
                ["TxtTicketChild"] = "1m-1.3m: 40.000₫",
                ["TxtTicketAdult"] = "Di atas 1.3m: 60.000₫",
                ["TxtChooseTour"] = "PILIH TUR ANDA",
                ["TxtViewAll"] = "Lihat semua",
                ["TxtTour1Title"] = "Kerajaan Gajah Asia",
                ["TxtTour2Title"] = "Raja Hutan",
                ["TxtTour3Title"] = "Raksasa Afrika",
                ["TxtListenNow"] = "🔊 DENGARKAN",
                ["TxtAnimalKingdom"] = "🌿 Kerajaan Hewan",
                ["TxtAnimalDesc"] = "Jelajahi dunia satwa liar",
                ["TxtSearchPlaceholder"] = "Cari hewan...",
                ["TxtInfo"] = "Info",
                ["TxtImages"] = "Galeri",
                ["TxtMap"] = "Peta",
                ["TxtEnclosure"] = "Lokasi Kandang",
                ["TxtNumpadTitle"] = "Masukkan Kode",
                ["TxtNumpadInstruction"] = "Masukkan kode di papan",
                ["TxtQrTitle"] = "Pindai di kandang",
                ["TxtQrInstruction"] = "Arahkan kamera ke QR",
                ["TxtQrSearching"] = "Mencari QR...",
                ["TxtFlash"] = "Flash",
                ["TxtManualCode"] = "Masukkan kode",
                ["TxtMapTitle"] = "🗺️ Peta Zoo",
                ["TxtAttractions"] = "Atraksi",
                ["TxtPoints"] = "titik",
                ["TxtListenBtn"] = "🔊 Dengar",
                ["TxtInZone"] = "● Di zona",
                ["TxtApproaching"] = "○ Mendekat",
                ["TxtAboutApp"] = "Tentang",
                ["TxtAppVersion"] = "Versi 1.0.0",
                ["TxtAboutTitle"] = "Tentang aplikasi",
                ["TxtAboutDesc"] = "Panduan audio cerdas untuk Kebun Binatang Saigon.",
                ["TxtDeveloper"] = "Dikembangkan oleh: Dũng Nguyễn",
                ["TxtAppInfo"] = "Info Aplikasi",
            },
            "ms" => new()
            {
                ["TabHome"] = "Utama",
                ["TabQR"] = "Imbas QR",
                ["TabNumpad"] = "Kod",
                ["TabStory"] = "Haiwan",
                ["TabMap"] = "Peta",
                ["TabAbout"] = "Tentang",
                ["TxtZooName"] = "ZOO SAIGON",
                ["TxtAudioGuide"] = "PANDUAN AUDIO LAWATAN",
                ["TxtHeroTitle"] = "Perjalanan Bunyi",
                ["TxtHeroAddress"] = "2 Nguyen Binh Khiem",
                ["TxtStartTour"] = "MULAKAN PERJALANAN  ▶",
                ["TxtOpenHours"] = "🕐 Waktu Buka",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "Buka setiap hari",
                ["TxtTicketTitle"] = "🎟️ Harga Tiket",
                ["TxtTicketFree"] = "Bawah 1m: Percuma",
                ["TxtTicketChild"] = "1m-1.3m: 40,000₫",
                ["TxtTicketAdult"] = "Atas 1.3m: 60,000₫",
                ["TxtChooseTour"] = "PILIH LAWATAN ANDA",
                ["TxtViewAll"] = "Lihat semua",
                ["TxtTour1Title"] = "Kerajaan Gajah Asia",
                ["TxtTour2Title"] = "Raja Rimba",
                ["TxtTour3Title"] = "Gergasi Afrika",
                ["TxtListenNow"] = "🔊 DENGAR",
                ["TxtAnimalKingdom"] = "🌿 Kerajaan Haiwan",
                ["TxtAnimalDesc"] = "Teroka dunia hidupan liar",
                ["TxtSearchPlaceholder"] = "Cari haiwan...",
                ["TxtInfo"] = "Maklumat",
                ["TxtImages"] = "Galeri",
                ["TxtMap"] = "Peta",
                ["TxtEnclosure"] = "Lokasi Kandang",
                ["TxtNumpadTitle"] = "Masukkan Kod",
                ["TxtNumpadInstruction"] = "Masukkan kod pada papan tanda",
                ["TxtQrTitle"] = "Imbas di kandang",
                ["TxtQrInstruction"] = "Arahkan kamera ke QR",
                ["TxtQrSearching"] = "Mencari QR...",
                ["TxtFlash"] = "Suluh",
                ["TxtManualCode"] = "Masukkan kod",
                ["TxtMapTitle"] = "🗺️ Peta Zoo",
                ["TxtAttractions"] = "Tarikan",
                ["TxtPoints"] = "titik",
                ["TxtListenBtn"] = "🔊 Dengar",
                ["TxtInZone"] = "● Dalam zon",
                ["TxtApproaching"] = "○ Menghampiri",
                ["TxtAboutApp"] = "Tentang",
                ["TxtAppVersion"] = "Versi 1.0.0",
                ["TxtAboutTitle"] = "Tentang aplikasi",
                ["TxtAboutDesc"] = "Panduan audio pintar untuk Zoo Saigon.",
                ["TxtDeveloper"] = "Dibangunkan oleh: Dũng Nguyễn",
                ["TxtAppInfo"] = "Maklumat Aplikasi",
            },
            "km" => new()
            {
                ["TabHome"] = "ទំព័រដើម",
                ["TabQR"] = "ស្កេន QR",
                ["TabNumpad"] = "លេខកូដ",
                ["TabStory"] = "សត្វ",
                ["TabMap"] = "ផែនទី",
                ["TabAbout"] = "អំពី",
                ["TxtZooName"] = "សួនសត្វសៃហ្គន",
                ["TxtAudioGuide"] = "ណែនាំជាសំឡេង",
                ["TxtHeroTitle"] = "ដំណើរសំឡេង",
                ["TxtHeroAddress"] = "2 Nguyen Binh Khiem",
                ["TxtStartTour"] = "ចាប់ផ្តើមដំណើរ  ▶",
                ["TxtOpenHours"] = "🕐 ម៉ោងបើក",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "បើករៀងរាល់ថ្ងៃ",
                ["TxtTicketTitle"] = "🎟️ តម្លៃសំបុត្រ",
                ["TxtTicketFree"] = "ក្រោម 1ម: ឥតគិតថ្លៃ",
                ["TxtTicketChild"] = "1ម-1.3ម: 40,000₫",
                ["TxtTicketAdult"] = "លើ 1.3ម: 60,000₫",
                ["TxtChooseTour"] = "ជ្រើសរើសដំណើរ",
                ["TxtViewAll"] = "មើលទាំងអស់",
                ["TxtTour1Title"] = "នគរដំរីអាស៊ី",
                ["TxtTour2Title"] = "ស្ដេចព្រៃ",
                ["TxtTour3Title"] = "យក្សអាហ្វ្រិក",
                ["TxtListenNow"] = "🔊 ស្ដាប់ឥឡូវ",
                ["TxtAnimalKingdom"] = "🌿 នគរសត្វ",
                ["TxtAnimalDesc"] = "រុករកពិភពសត្វព្រៃ",
                ["TxtSearchPlaceholder"] = "ស្វែងរកសត្វ...",
                ["TxtInfo"] = "ព័ត៌មាន",
                ["TxtImages"] = "រូបភាព",
                ["TxtMap"] = "ផែនទី",
                ["TxtEnclosure"] = "ទីតាំងទ្រុង",
                ["TxtNumpadTitle"] = "បញ្ចូលកូដ",
                ["TxtNumpadInstruction"] = "បញ្ចូលកូដបនប្រកាស",
                ["TxtQrTitle"] = "ស្កេននៅទ្រុង",
                ["TxtQrInstruction"] = "ចង្អុលកាមេរ៉ា QR",
                ["TxtQrSearching"] = "កំពុងស្វែងរក QR...",
                ["TxtFlash"] = "ភ្លើង",
                ["TxtManualCode"] = "បញ្ចូលកូដ",
                ["TxtMapTitle"] = "🗺️ ផែនទីសួនសត្វ",
                ["TxtAttractions"] = "ទីតាំង",
                ["TxtPoints"] = "ចំណុច",
                ["TxtListenBtn"] = "🔊 ស្ដាប់",
                ["TxtInZone"] = "● នៅតំបន់",
                ["TxtApproaching"] = "○ កំពុងជិតដល់",
                ["TxtAboutApp"] = "អំពី",
                ["TxtAppVersion"] = "កំណែ 1.0.0",
                ["TxtAboutTitle"] = "អំពីកម្មវិធី",
                ["TxtAboutDesc"] = "ណែនាំជាសំឡេងឆ្លាតសំរាប់សួនសត្វសៃហ្គន",
                ["TxtDeveloper"] = "បង្កើតដោយ: Dũng Nguyễn",
                ["TxtAppInfo"] = "ព័ត៌មានកម្មវិធី",
            },
            _ => new() // tiếng Việt
            {
                ["TabHome"] = "Trang chủ",
                ["TabQR"] = "Mã QR",
                ["TabNumpad"] = "Nhập Số",
                ["TabStory"] = "Câu chuyện",
                ["TabMap"] = "Sơ đồ",
                ["TabAbout"] = "Giới thiệu",
                ["TxtZooName"] = "THẢO CẦM VIÊN SÀI GÒN",
                ["TxtAudioGuide"] = "AUDIO GUIDE TOUR",
                ["TxtHeroTitle"] = "Hành Trình Âm Thanh",
                ["TxtHeroAddress"] = "2 Nguyễn Bỉnh Khiêm, Quận 1",
                ["TxtStartTour"] = "BẮT ĐẦU CHUYẾN ĐI  ▶",
                ["TxtOpenHours"] = "🕐 Giờ mở cửa",
                ["TxtHoursDetail"] = "7:00 - 18:30",
                ["TxtHoursNote"] = "Mở cửa tất cả các ngày",
                ["TxtTicketTitle"] = "🎟️ Vé vào cổng",
                ["TxtTicketFree"] = "Dưới 1m: Miễn phí",
                ["TxtTicketChild"] = "1m - 1m3: 40.000đ",
                ["TxtTicketAdult"] = "Trên 1m3: 60.000đ",
                ["TxtChooseTour"] = "CHỌN TOUR CỦA BẠN",
                ["TxtViewAll"] = "Xem tất cả",
                ["TxtTour1Title"] = "Vương Quốc Voi Châu Á",
                ["TxtTour2Title"] = "Chúa Tể Sơn Lâm",
                ["TxtTour3Title"] = "Gã Khổng Lồ Châu Phi",
                ["TxtListenNow"] = "🔊 NGHE NGAY",
                ["TxtVoice"] = "Giọng đọc",
                ["TxtLyrics"] = "Lời thoại",
                ["TxtHappeningNow"] = "Đang diễn ra ngay lúc này",
                ["TxtRecommendedForYou"] = "Gợi ý cho bạn",
                ["TxtWeatherAtZoo"] = "Thời tiết tại Thảo Cầm Viên",
                ["TxtAnimalKingdom"] = "🌿 Vương quốc động vật",
                ["TxtAnimalDesc"] = "Khám phá thế giới muôn loài tuyệt đẹp tại Thảo Cầm Viên",
                ["TxtSearchPlaceholder"] = "Tìm kiếm động vật...",
                ["TxtInfo"] = "Thông tin",
                ["TxtImages"] = "Hình ảnh",
                ["TxtMap"] = "Bản đồ",
                ["TxtEnclosure"] = "Vị trí chuồng nuôi",
                ["TxtNumpadTitle"] = "Nhập mã số",
                ["TxtNumpadInstruction"] = "Nhập mã trên biển báo",
                ["TxtQrTitle"] = "Quét mã tại chuồng thú",
                ["TxtQrInstruction"] = "Hướng camera vào mã QR",
                ["TxtQrSearching"] = "Đang tìm kiếm mã QR...",
                ["TxtFlash"] = "Bật đèn",
                ["TxtManualCode"] = "Nhập mã tay",
                ["TxtMapTitle"] = "🗺️ Bản đồ Thảo Cầm Viên",
                ["TxtAttractions"] = "Các điểm tham quan",
                ["TxtPoints"] = "điểm",
                ["TxtListenBtn"] = "🔊 Nghe",
                ["TxtInZone"] = "● Trong vùng",
                ["TxtApproaching"] = "○ Đang tiếp cận",
                ["TxtAboutApp"] = "Giới thiệu",
                ["TxtAppVersion"] = "Phiên bản 1.0.0",
                ["TxtAboutTitle"] = "Về ứng dụng",
                ["TxtAboutDesc"] = "Ứng dụng hướng dẫn tham quan Thảo Cầm Viên thông minh. GPS tự động, QR code, đa ngôn ngữ.",
                ["TxtDeveloper"] = "Phát triển bởi: Dũng Nguyễn",
                ["TxtAppInfo"] = "Thông tin ứng dụng",
            }
        };
    }
}
