namespace AppThaoCamVien.Services;

/// <summary>
/// Chuỗi onboarding + offline sync (vi / en / ja). Gộp vào Application.Resources qua LanguageManager.Apply.
/// </summary>
public static class OnboardingStringCatalog
{
    public static IReadOnlyDictionary<string, string> ForLang(string lang) => lang switch
    {
        "en" => En(),
        "ja" => Ja(),
        _ => Vi(),
    };

    private static Dictionary<string, string> Vi() => new()
    {
        ["OnboardingWelcomeTitle"] = "Thảo Cầm Viên",
        ["OnboardingWelcomeBody"] = "Trải nghiệm khám phá hoàn toàn mới với hướng dẫn viên tự động theo vị trí — phù hợp khi bạn đi bộ ngoài trời.",
        ["OnboardingCtaStart"] = "Bắt đầu khám phá",
        ["OnboardingPermTitle"] = "Cho phép để tự động thuyết minh",
        ["OnboardingPermSubtitle"] = "Chúng tôi chỉ dùng quyền khi cần, và giải thích rõ lý do trước khi hệ điều hành hiện hộp thoại.",
        ["OnboardingPermLocationTitle"] = "Định vị (kể cả khi tắt màn hình)",
        ["OnboardingPermLocationBody"] = "Để ứng dụng tự động phát audio khi bạn đến các khu thú, chúng tôi cần vị trí liên tục. Bạn có thể tối ưu pin trong Cài đặt.",
        ["OnboardingPermLocationBtn"] = "Cho phép định vị",
        ["OnboardingPermNotifTitle"] = "Thông báo",
        ["OnboardingPermNotifBody"] = "Nhận thông báo khi có điểm tham quan mới gần bạn hoặc khi dịch vụ định vị chạy nền.",
        ["OnboardingPermNotifBtn"] = "Bật thông báo",
        ["OnboardingPermContinue"] = "Tiếp tục",
        ["OnboardingPermSkipped"] = "Một số quyền chưa được cấp — bạn có thể bật lại trong Cài đặt hệ thống.",
        ["OnboardingOfflineTitle"] = "Tải dữ liệu offline",
        ["OnboardingOfflineSubtitle"] = "Bản đồ, audio và kịch bản TTS để tham quan không phụ thuộc mạng.",
        ["OnboardingLangLabel"] = "Ngôn ngữ gói tải",
        ["OnboardingPkgMap"] = "Dữ liệu bản đồ",
        ["OnboardingPkgAudio"] = "File audio thuyết minh",
        ["OnboardingPkgTts"] = "Kịch bản TTS",
        ["OnboardingTotalSize"] = "Tổng dung lượng ước tính",
        ["OnboardingDownloadBtn"] = "Tải xuống",
        ["OnboardingSkipLater"] = "Bỏ qua, tải sau",
        ["OnboardingSkipWarnTitle"] = "Dùng dữ liệu qua mạng?",
        ["OnboardingSkipWarnMessage"] = "Nếu chưa tải offline, ứng dụng có thể phát stream qua 3G/4G/5G và tốn dữ liệu di động khi tham quan.",
        ["OnboardingSkipWarnCancel"] = "Quay lại",
        ["OnboardingSkipWarnOk"] = "Vẫn bỏ qua",
        ["OnboardingProgressHint"] = "Đang chuẩn bị hành trang… Sau khi xong, bạn không tốn dữ liệu mạng khi tham quan trong công viên.",
        ["OnboardingResumeDownload"] = "Tiếp tục tải",
        ["OnboardingNetworkLost"] = "Mất kết nối — đã lưu {0}. Chạm \"Tiếp tục tải\" khi có mạng trở lại.",
        ["OnboardingDownloadComplete"] = "Tải xong. Chào mừng bạn đến với hành trình!",
        ["OnboardingDownloading"] = "Đang tải…",
        ["OnboardingOfflinePaused"] = "Đã tạm dừng",
        ["OnboardingPercentFormat"] = "{0:0}%",
        ["OnboardingEnterApp"] = "Vào ứng dụng",
    };

    private static Dictionary<string, string> En() => new()
    {
        ["OnboardingWelcomeTitle"] = "Saigon Zoo & Botanical Gardens",
        ["OnboardingWelcomeBody"] = "A new way to explore with automatic audio guidance based on your location — built for walking outdoors.",
        ["OnboardingCtaStart"] = "Start exploring",
        ["OnboardingPermTitle"] = "Permissions for automatic narration",
        ["OnboardingPermSubtitle"] = "We explain why we need each permission before the system dialog appears.",
        ["OnboardingPermLocationTitle"] = "Location (including in background)",
        ["OnboardingPermLocationBody"] = "To play audio when you reach animal zones, we need continuous location. You can optimize battery in Settings.",
        ["OnboardingPermLocationBtn"] = "Allow location",
        ["OnboardingPermNotifTitle"] = "Notifications",
        ["OnboardingPermNotifBody"] = "Get notified about new nearby points of interest or when location runs in the background.",
        ["OnboardingPermNotifBtn"] = "Enable notifications",
        ["OnboardingPermContinue"] = "Continue",
        ["OnboardingPermSkipped"] = "Some permissions are still off — you can enable them later in system Settings.",
        ["OnboardingOfflineTitle"] = "Offline download",
        ["OnboardingOfflineSubtitle"] = "Map tiles, narration audio and TTS scripts so your visit does not depend on the network.",
        ["OnboardingLangLabel"] = "Package language",
        ["OnboardingPkgMap"] = "Map data",
        ["OnboardingPkgAudio"] = "Narration audio",
        ["OnboardingPkgTts"] = "TTS scripts",
        ["OnboardingTotalSize"] = "Estimated total size",
        ["OnboardingDownloadBtn"] = "Download",
        ["OnboardingSkipLater"] = "Skip for now",
        ["OnboardingSkipWarnTitle"] = "Use streamed data?",
        ["OnboardingSkipWarnMessage"] = "Without offline data, the app may stream over 3G/4G/5G and use mobile data during your visit.",
        ["OnboardingSkipWarnCancel"] = "Go back",
        ["OnboardingSkipWarnOk"] = "Skip anyway",
        ["OnboardingProgressHint"] = "Preparing your visit… After this, you can tour the zoo without using mobile data.",
        ["OnboardingResumeDownload"] = "Resume download",
        ["OnboardingNetworkLost"] = "Connection lost — saved {0}. Tap \"Resume download\" when you are back online.",
        ["OnboardingDownloadComplete"] = "All set. Enjoy your journey!",
        ["OnboardingDownloading"] = "Downloading…",
        ["OnboardingOfflinePaused"] = "Paused",
        ["OnboardingPercentFormat"] = "{0:0}%",
        ["OnboardingEnterApp"] = "Enter app",
    };

    private static Dictionary<string, string> Ja() => new()
    {
        ["OnboardingWelcomeTitle"] = "サイゴン動植物園",
        ["OnboardingWelcomeBody"] = "位置情報に合わせて音声ガイドが自動再生 — 屋外の散策に最適です。",
        ["OnboardingCtaStart"] = "はじめる",
        ["OnboardingPermTitle"] = "自動解説のための権限",
        ["OnboardingPermSubtitle"] = "OSの許可画面の前に、理由を説明します。",
        ["OnboardingPermLocationTitle"] = "位置情報（バックグラウンド含む）",
        ["OnboardingPermLocationBody"] = "エリアに入ったときに音声を再生するため、継続的な位置情報が必要です。設定で省電力にできます。",
        ["OnboardingPermLocationBtn"] = "位置情報を許可",
        ["OnboardingPermNotifTitle"] = "通知",
        ["OnboardingPermNotifBody"] = "近くの新しい見どころや、バックグラウンド位置の案内のための通知です。",
        ["OnboardingPermNotifBtn"] = "通知をオン",
        ["OnboardingPermContinue"] = "次へ",
        ["OnboardingPermSkipped"] = "未許可の項目があります — 後から設定で変更できます。",
        ["OnboardingOfflineTitle"] = "オフライン取得",
        ["OnboardingOfflineSubtitle"] = "地図・音声・TTS台本を端末に保存し、圏外でも快適に。",
        ["OnboardingLangLabel"] = "パッケージ言語",
        ["OnboardingPkgMap"] = "地図データ",
        ["OnboardingPkgAudio"] = "解説音声",
        ["OnboardingPkgTts"] = "TTS台本",
        ["OnboardingTotalSize"] = "推定合計サイズ",
        ["OnboardingDownloadBtn"] = "ダウンロード",
        ["OnboardingSkipLater"] = "あとで",
        ["OnboardingSkipWarnTitle"] = "通信を使いますか？",
        ["OnboardingSkipWarnMessage"] = "オフライン未取得の場合、3G/4G/5Gでストリーミングし、通信量を消費することがあります。",
        ["OnboardingSkipWarnCancel"] = "戻る",
        ["OnboardingSkipWarnOk"] = "スキップする",
        ["OnboardingProgressHint"] = "準備中です… 完了後は園内でモバイルデータをほぼ使いません。",
        ["OnboardingResumeDownload"] = "再開",
        ["OnboardingNetworkLost"] = "接続が切れました — {0} まで保存済み。回復したら「再開」を押してください。",
        ["OnboardingDownloadComplete"] = "準備完了。良い旅を！",
        ["OnboardingDownloading"] = "ダウンロード中…",
        ["OnboardingOfflinePaused"] = "一時停止",
        ["OnboardingPercentFormat"] = "{0:0}%",
        ["OnboardingEnterApp"] = "アプリへ",
    };
}
